version: '3.8'
services:
  testapi:
    build:
      context: ../TestAPI
      dockerfile: Dockerfile
    ports:
      - "5215:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5271:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - TestApi_BaseUrl=http://testapi:8080
    depends_on:
      - testapi